### ISSUE TITLE
HTTP GET doesn't seem to work...

### ISSUE THREAD

**Issue by everythingability** [flydelabs/flyde#118]
I do this...

<img width="747" alt="image" src="https://github.com/flydelabs/flyde/assets/96276/c0983e99-94b1-44de-9038-8e3d9735c505">

Where the URL is https://randomfox.ca/floof/

And get... (sorry can't copy out of the JSON parse node)

![image](https://github.com/flydelabs/flyde/assets/96276/f6e3b036-3728-4f25-b90e-6142d06703f9)

Tom

**Comment by GabiGrin** [comment]
Hey Tom,
The response of the HTTP is a valid JSON already so you don't need to parse it.
You can immediately use the "get attribute" node to extract your needed info.

See example:
https://github.com/flydelabs/flyde/assets/3727015/6c72e2ac-5504-41b3-85d0-f21d255ce0c2

Let me know if that helps!

**Comment by everythingability** [comment]
It does. Brilliant! Thank you...

Next up... why can't I delete links between nodes? I also don't think the
value bit should show/hide.

And when I've used up the two inputs on a Concat, another input should
appear - and so on. Chaining multiple Concats is no way to work.

**Comment by everythingability** [comment]
Just a thought, but why isn't there a webserver component? And a SQLite
component would be nice.

Drag it in, set its host and port... and it has a HTTP Request value that
comes out. I build a HTTP Request object and plop it in the result.

If I could then somehow boil this down to a full node.js project that I
could save to github and deploy to Glitch.com I'd have a great teaching /
noodling / development tool.  Like Prograph in the old days :-)

Thanks again

Tom

**Comment by GabiGrin** [comment]
Hey Tom,
Great q's and feedback as always!

- **Removing connections** -  I just noticed that #116, which fixed the issue you've reported #107 wasn't published! I'm publishing it to the vscode 
- **value bit show/hide** - which one are you referring to? I have a feeling I know what you're talking about as I feet it's too jumpy / hidden sometimes, but wanna make sure we're on the same page :)
- **concat** - that's correct! at the minimum, I can make the inputs count configurable. Btw, concat is a controversial node - as it's probably better to use a bit of inline code:
![Screenshot 2024-05-08 at 16 05 35](https://github.com/flydelabs/flyde/assets/3727015/ab93fee8-1a1b-4738-91bd-77cda196ccb5) it uses JS's [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) and Flyde's inline code automatic input generation (each time you use "inputs.X" an input will be exposed to achieve a custom concat. wondering about your thoughts here

- **webserver** - you could wrap up a Flyde flow in a simple node.js express server pretty easily. I think that's a really mandatory tutorial I should have - or even a CLI helper to generate it, but in a nutshell, the webserver component can't be in Flyde because it needs to be "outside" of the level of the flow. Or I might come with a better solution in the future
- **SQL** - there's some postgres / mongo built in nodes, but TBH they are not heavily tested. Which one are you using? would love to make sure you have the nodes you need to run stuff!
- re: Glitch deployment - it's a great idea, especially if Glitch somehow adds support for Flyde projects. I have a https://railway.app/ be somewhat close to what you're trying to achieve, and building a more specific tool at https://www.trigg.dev to help building one-off apis with Flyde

**Comment by GabiGrin** [comment]
Hey @everythingability  wondering if you had a chance to see my response - would love to know if it makes sense

**Comment by everythingability** [comment]
Ah thanks, and apologies, I thought I'd replied... so sorry.

I got lost in just messing about with Flyde... :-)

**Comment by GabiGrin** [comment]
@everythingability haha no worries :) if something there doesn't quite make sense, let me know!
